### ISSUE TITLE
Is it possible to make a new release

### ISSUE THREAD

**Issue by amutu** [ChristophBerg/pg_dirtyread#1]
Hi  Christoph，
  It is great that you maintain the pg_dirtyread extension, thanks to your work!. I am working in progress to port this extension to FreeBSD, one problem is the version of this port, you do a lot of bug fixes but there is no new release. Is it possible to make a new release?

more info: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=220537#c2

Thanks!

**Comment by df7cb** [comment]
Hi,
I wanted to recheck with the original authors before releasing a forked version, but that should happen really soon now. I'd expect to make a release next week.
Thanks!

**Comment by amutu** [comment]
Hi, is there anything I can do to make the new release out？

**Comment by df7cb** [comment]
Done now, thanks for the poke :)

**Comment by t-zuehlsdorff** [comment]
Thanks to both of you. I just committed the port to the FreeBSD ports-tree:
http://www.freshports.org/databases/pg_dirtyread
