### ISSUE TITLE
Why can't I look at the example and see  [baz] column:  delete update  ? 

### ISSUE THREAD

**Issue by cityvigil** [ChristophBerg/pg_dirtyread#12]
[pg12@client1 extension]$ psql -V
psql (PostgreSQL) 12.7
[pg12@client1 extension]$ 

pg_dirtyread-2.2

###################################

mydb=# \d t1
                        Table "public.t1"
 Column |         Type          | Collation | Nullable | Default 
--------+-----------------------+-----------+----------+---------
 id     | integer               |           |          | 
 name   | character varying(10) |           |          |

mydb=# select * from pg_dirtyread('t1') as recovery_t(id int,name varchar(10));
 id | name 
----+------
  4 | d
  3 | cc
  3 | cc
(3 rows)

mydb=# SELECT * FROM pg_dirtyread('t1')
mydb-#       AS t(tableoid oid, ctid tid, xmin xid, xmax xid, cmin cid, cmax cid, dead boolean,
mydb(#            id int, name varchar(10));
 tableoid | ctid  | xmin | xmax | cmin | cmax | dead | id | name 
----------+-------+------+------+------+------+------+----+------
    16386 | (0,1) |  493 |  500 |    0 |    0 | t    |  4 | d
    16386 | (0,2) |  497 |    0 |    0 |    0 | t    |  3 | cc
    16386 | (0,3) |  498 |    0 |    0 |    0 | t    |  3 | cc
(3 rows)

----- Why can't I look at the example and see  [baz] column:  delete update  ? 

  SELECT * FROM pg_dirtyread('foo')
      AS t(tableoid oid, ctid tid, xmin xid, xmax xid, cmin cid, cmax cid, dead boolean,
           bar bigint, baz text);
   tableoid │ ctid  │ xmin │ xmax │ cmin │ cmax │ dead │ bar │        baz
  ──────────┼───────┼──────┼──────┼──────┼──────┼──────┼─────┼───────────────────
      41823 │ (0,1) │ 1484 │ 1485 │    0 │    0 │ t    │   1 │ Delete
      41823 │ (0,2) │ 1484 │    0 │    0 │    0 │ f    │   2 │ Insert
      41823 │ (0,3) │ 1484 │ 1486 │    0 │    0 │ t    │   3 │ Update

**Comment by df7cb** [comment]
Sorry I don't understand the question. What did you do to get to the last output? Did you make sure autovacuum isn't spoiling it?

**Comment by cityvigil** [comment]
Thank you for your reply.

I've copied the example from the "System Columns" section of README.md. 

I thought the column **baz**  would indicate which type of dml statement was used to manipulate this row.

My question is：

The "baz" column is actually the real value of the table , not the dml operation type of this record ?





mydb=# CREATE TABLE foo (bar bigint, baz text);
CREATE TABLE
mydb=#   ALTER TABLE foo SET (
mydb(#     autovacuum_enabled = false, toast.autovacuum_enabled = false
mydb(#   );
ALTER TABLE
mydb=# 
mydb=#  INSERT INTO foo VALUES (1, 'Test'), (2, 'New Test');
INSERT 0 2
mydb=#   select *from foo; 
 bar |   baz    
-----+----------
   1 | Test
   2 | New Test
(2 rows)

mydb=#  DELETE FROM foo WHERE bar = 1;
DELETE 1
mydb=# 
mydb=#  SELECT * FROM pg_dirtyread('foo') as t(bar bigint, baz text);
 bar |   baz    
-----+----------
   1 | Test
   2 | New Test
(2 rows)

mydb=#  
mydb=# SELECT * FROM pg_dirtyread('foo')
mydb-#       AS t(tableoid oid, ctid tid, xmin xid, xmax xid, cmin cid, cmax cid, dead boolean,
mydb(#            bar bigint, baz text);
 tableoid | ctid  | xmin | xmax | cmin | cmax | dead | bar |   baz    
----------+-------+------+------+------+------+------+-----+----------
    16453   | (0,1)    |  504   |  505   |    0     |    0      | f       |   1       | **Test               <<<<<   I thought this would reflect the type of dml operation. For example (insert , update , delete )**
    16453   | (0,2)   |  504   |    0     |    0     |    0       | f       |   2      | New Test
(2 rows)




mydb=#   select * from foo; 
 bar |   baz    
-----+----------
   2 | New Test
(1 row)

**Comment by df7cb** [comment]
"baz" is a normal column and it's containing "insert" and "update" only because these strings were explicitly inserted.

**Comment by cityvigil** [comment]
thanks
