### ISSUE TITLE
Getting error converting tuple descriptors

### ISSUE THREAD

**Issue by marcelobaxauli** [ChristophBerg/pg_dirtyread#13]
Hello, I'm trying to execute this query:

    SELECT * FROM pg_dirtyread('pg_catalog.pg_constraint') 
	   as (oid oid, conname name, connamespace oid, contype char);

But I'm getting the following error:

SQL Error [42804]: ERROR: Error converting tuple descriptors!
  Detail: Attribute "contype" has type "char" in corresponding attribute of type pg_constraint.

I'm using Postgres 12.11 for Ubuntu.

Seems like an error converting the type char...
Any ideas or solutions?

Thanks;

**Comment by df7cb** [comment]
Hi,
"char" is a weird datatype in PostgreSQL, there is `char(N)` from the SQL standard, and there is `"char"` which is a 1-byte fixed-size type used in pg_catalog. You have the latter here - to use it, include the "quotes": `... contype "char"`.

**Comment by marcelobaxauli** [comment]
That did the trick, thanks;
