### ISSUE TITLE
Could not open extension control file

### ISSUE THREAD

**Issue by Raquel10-RevenueCat** [ChristophBerg/pg_dirtyread#14]
I am using MacOS Monterey and PostgreSQL 14. I am getting the following error when I run `CREATE EXTENSION pg_dirtyread;`:

```
[58P01] ERROR: could not open extension control file "/rdsdbbin/postgres-14.4.R1/share/extension/pg_dirtyread.control": No such file or directory
```

Any idea why can this be? Installation with make went on successfully.

Thanks a lot!

**Comment by df7cb** [comment]
Did you use the correct `pg_config` binary for the compilation and installation? If there are several PG installations on that system, it might have installed into the wrong `extension` directory.

```
make PG_CONFIG=/path/to/pg_config
make install PG_CONFIG=/path/to/pg_config
make installcheck PG_CONFIG=/path/to/pg_config
```
