### ISSUE TITLE
when I execute 'make' to build pg_dirtyread，I met a question 'gcc: fatal error: cannot specify ‘-o’ with ‘-c’, ‘-S’ or ‘-E’ with multiple files'

### ISSUE THREAD

**Issue by Chow0919** [ChristophBerg/pg_dirtyread#15]
[root@iZ2vc2iy7g5tupvfss5hdkZ pg_dirtyread-master]# make
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wshadow=compatible-local -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -fPIC -fvisibility=hidden /data/postgresql/postgresql-16.3/src/include/postgres.h -I. -I./ -I/usr/include/pgsql/server -I/usr/include/pgsql/internal  -D_GNU_SOURCE   -c -o pg_dirtyread.o pg_dirtyread.c
gcc: fatal error: cannot specify ‘-o’ with ‘-c’, ‘-S’ or ‘-E’ with multiple files
compilation terminated.
make: *** [<builtin>: pg_dirtyread.o] Error 1
-----------------
you know why?

**Comment by df7cb** [comment]
My guess would be on this extra blank between -D and -c: `-D_GNU_SOURCE   -c`

But I have this here as well and the compiler (gcc 13.2) does not complain.

**Comment by df7cb** [comment]
Where does that `/data/postgresql/postgresql-16.3/src/include/postgres.h` come from? That's something bad in your environment.

**Comment by Chow0919** [comment]
ok i will check pg's environment tommorrow.
thank you
---- Replied Message ----
| From | Christoph ***@***.***> |
| Date | 05/21/2024 22:45 |
| To | df7cb/pg_dirtyread ***@***.***> |
| Cc | Chow0919 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [df7cb/pg_dirtyread] when I execute 'make' to build pg_dirtyread，I met a question 'gcc: fatal error: cannot specify ‘-o’ with ‘-c’, ‘-S’ or ‘-E’ with multiple files' (Issue #15) |

Where does that /data/postgresql/postgresql-16.3/src/include/postgres.h come from? That's something bad in your environment.
