### ISSUE TITLE
Recovery deleted data from Postgresql 8.2

### ISSUE THREAD

**Issue by moabson** [ChristophBerg/pg_dirtyread#3]
Is it possible to install pg_dirtyread in Postgresql 8.2?

**Comment by df7cb** [comment]
8.2 doesn't have access/tupconvert.h so compilation fails. There's a chance that this is trivially fixable because the needed functionality from there is just in a different header file, but this is likely not the only problem.
Do you want to give patching it a try?

**Comment by moabson** [comment]
I installed libpq-dev (pg_conf for ver 8.4) and i created symbolic links to 8.2 folders, tupconvert.h and sysattr.h file are copied  to /usr/include/postgresql/8.2/server/access/. I succeeded on run "make" and "make install". However version 8.2 does not have support for "CREATE EXTENSION" command.

**Comment by moabson** [comment]
I succeeded and tested on Postgresql 9.6 over Ubuntu 17.04 (Test environment).

**Comment by moabson** [comment]
psql -U postgres -d aplicacao -f execute.sql

_execute.sql_
**CREATE FUNCTION** pg_dirtyread(oid)
**RETURNS** setof record
**AS** '/usr/lib/postgresql/8.3/lib/pg_dirtyread'
LANGUAGE C;

psql:execute.sql:4: ERRO:  não pôde carregar biblioteca "/usr/lib/postgresql/8.3/lib/pg_dirtyread.so": /usr/lib/postgresql/8.3/lib/pg_dirtyread.so: undefined symbol: HeapTupleIsSurelyDead

**Comment by df7cb** [comment]
Btw, the newest pg_filedump can decode tuples as well, that might have more chances of working on 8.2 without much patching.

**Comment by df7cb** [comment]
@moabson: could you recover the data?

**Comment by moabson** [comment]
I did not succeed in recovery, many problems were encountered in trying to run on an old version of postgresql. In new versions of postgresql worked well. The knowledge acquired was good.

Thanks.
