### ISSUE TITLE
Version match problem

### ISSUE THREAD

**Issue by soliergashev** [ChristophBerg/pg_dirtyread#6]
ERROR:  incompatible library "/usr/pgsql-9.6/lib/pg_dirtyread.so": version mismatch
DETAIL:  Server is version 9.6, library is version 9.2.
 How to resolve this issue?

**Comment by df7cb** [comment]
You need to compile the module for 9.6, not for 9.2.

make PG_CONFIG=/path/to/9.6/bin/pg_config
