### ISSUE TITLE
LOG:  server process (PID 30035) was terminated by signal 11: Segmentation fault

### ISSUE THREAD

**Issue by di-dimitrov** [ChristophBerg/pg_dirtyread#8]
After executing  postgres@pybossa LOG:  statement: select * from pg_dirtyread(...)
I get the following error in my logs:
`2021-01-16 22:54:07.403 EET [29991] LOG:  server process (PID 30035) was terminated by signal 11: Segmentation fault`
`2021-01-16 22:54:07.403 EET [29991] LOG:  terminating any other active server processes`
`2021-01-16 22:54:07.405 EET [30036] postgres@pybossa FATAL:  the database system is in recovery mode`
`2021-01-16 22:54:07.408 EET [29991] LOG:  all server processes terminated; reinitializing`

I read that this could be a RAM issue ... maybe because the table contains too many records (more than 10k and some of those are decently sized jsonb columns). I was wondering if you would know If I can backup the database and run pg_dirtyread() on a better machine. My issue is that I am not very familiar with the how the pg_dump works and if the unvacummed rows would be kept during the process.

I would really love some help on this :) Lost some important data :(

**Comment by df7cb** [comment]
Hi,
I'll need more details to be able to debug this.
* Which query were you running exactly?
* What's the table definition? (`\d tbl` in psql)
* Is any of the data toasted? (You said "decently sized jsonb", so likely yes.)
* Ideally, you should extract a backtrace. https://wiki.postgresql.org/wiki/Getting_a_stack_trace_of_a_running_PostgreSQL_backend_on_Linux/BSD

I'm not sure pg_dirtyread is ready yet to retrieve toasted columns, but invoking it on the toast table directly should work.

**Comment by df7cb** [comment]
Oh, and disable autovacuum on the table and the toast table.

**Comment by df7cb** [comment]
Please reopen if you have more information.
