### ISSUE TITLE
pg_dirtyread on windows?

### ISSUE THREAD

**Issue by telmedola** [ChristophBerg/pg_dirtyread#9]
Hi!
Please, is there any way to use pg_dirtyread for windows server?

**Comment by df7cb** [comment]
Hi,
I have zero experience with compiling on Windows. Google suggests that some extra steps are necessary: 

https://wiki.postgresql.org/wiki/Building_and_Installing_PostgreSQL_Extension_Modules
https://www.2ndquadrant.com/en/blog/compiling-postgresql-extensions-visual-studio-windows/

If that works for you and you have a patch that I should incorporate, please open a pull request.
